# docker-compose.yml

version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80' # Maps host port 3000 to container port 80 (Nginx)
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000' # Maps host port 5000 to container port 5000 (Express)
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add other environment variables as needed
    volumes:
      - ./server/shared/dist:/app/shared/dist # Mount shared types if needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge