services:
  nginx:
    container_name: snapcart-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-generate-cert.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/var/www/certbot
    networks:
      - app-network

  certbot:
    container_name: snapcart-certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - app-network
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email rahilsardar234@gmail.com
      --agree-tos
      --no-eff-email
      -d api.snapcart.website

networks:
  app-network:
    driver: bridge
