version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    ports:
      - "3000:3000" # Exposed for direct access if needed
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/letsencrypt  # Mount certificates
      - certbot-www:/var/www/certbot     # Mount webroot for ACME challenges
    depends_on:
      - node
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  certbot-www: